export const Data = [
  {
    id: 1,
    date: "28/09/22 21:30",
    location: "BYN.TBG",
    fasilitas: "Tangki Timbun",
    kode_tangki: "T.3",
    material: "B30",
    lobs: "1,498,071",
    l15: "1,481,517",
    barrel: "9,323.186",
    metric_ton: "1,268.802	",
    long_ton: "1,248.771",
    product_owner: "PT. Pertamina (Persero)",
    storage_owner: "PT Bayan Resource TBK (Tabang)",
    status: "Active",
  },
  {
    id: 2,
    date: "28/09/22 21:30",
    location: "BYN.TBG",
    fasilitas: "Tangki Timbun",
    kode_tangki: "T.3",
    material: "B30",
    lobs: "1,498,071",
    l15: "1,481,517",
    barrel: "9,323.186",
    metric_ton: "1,268.802	",
    long_ton: "1,248.771",
    product_owner: "PT. Pertamina (Persero)",
    storage_owner: "PT Bayan Resource TBK (Tabang)",
    status: "Active",
  },
  {
    id: 3,
    date: "28/09/22 21:30",
    location: "BYN.TBG",
    fasilitas: "Tangki Timbun",
    kode_tangki: "T.3",
    material: "B30",
    lobs: "1,498,071",
    l15: "1,481,517",
    barrel: "9,323.186",
    metric_ton: "1,268.802	",
    long_ton: "1,248.771",
    product_owner: "PT. Pertamina (Persero)",
    storage_owner: "PT Bayan Resource TBK (Tabang)",
    status: "Active",
  },
  {
    id: 4,
    date: "28/09/22 21:30",
    location: "BYN.TBG",
    fasilitas: "Tangki Timbun",
    kode_tangki: "T.3",
    material: "B30",
    lobs: "1,498,071",
    l15: "1,481,517",
    barrel: "9,323.186",
    metric_ton: "1,268.802	",
    long_ton: "1,248.771",
    product_owner: "PT. Pertamina (Persero)",
    storage_owner: "PT Bayan Resource TBK (Tabang)",
    status: "Active",
  },
];

export const DataHead = [
  {
    id: 1,
    name: "Last Update",
    row: 2,
  },
  {
    id: 2,
    name: "Location",
    row: 2,
  },
  {
    id: 3,
    name: "Fasilitas Simpan",
    row: 2,
  },
  {
    id: 4,
    name: "#",
    row: 2,
  },
  {
    id: 5,
    name: "Material",
    row: 2,
  },
  {
    id: 6,
    name: "Volumes",
    col: 5,
  },
  {
    id: 7,
    name: "Product Owner",
    row: 2,
  },
  {
    id: 8,
    name: "Storage Owner",
    row: 2,
  },
  {
    id: 9,
    name: "Status",
    row: 2,
  },
  {
    id: 10,
    name: "LObs (L)",
    row: 1,
  },
  {
    id: 11,
    name: "L15 (L)",
    row: 1,
  },
  {
    id: 12,
    name: "Barrel",
    row: 1,
  },
  {
    id: 13,
    name: "MT",
    row: 1,
  },
  {
    id: 14,
    name: "LT",
    row: 1,
  },
];
